# Generated by Django 5.1.3 on 2024-11-28 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('M', 'Typem'), ('MM', 'Typemm'), ('R', 'Typer'), ('RR', 'Typerm')], default='M', max_length=2)),
                ('difficulty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('S', 'SUCCEED'), ('F', 'FAILED'), ('A', 'AVAILABLE'), ('U', 'UNAVAILABLE')], default='U', max_length=2)),
                ('r_score', models.IntegerField()),
                ('node_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercices', to='apppl.node')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices', to='apppl.student')),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('question', models.CharField(max_length=255)),
                ('solution', models.CharField(max_length=255)),
                ('student_answer', models.CharField(max_length=255)),
                ('distance', models.IntegerField()),
                ('exercice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='apppl.exercice')),
            ],
        ),
    ]
