# Generated by Django 5.1.3 on 2024-11-28 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apppl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercice',
            old_name='node_id',
            new_name='node',
        ),
        migrations.RenameField(
            model_name='exercice',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='trial',
            old_name='exercice_id',
            new_name='exercice',
        ),
    ]
