# Generated by Django 5.1.3 on 2025-01-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='default_probabilty',
        ),
        migrations.AlterField(
            model_name='exercice',
            name='quality',
            field=models.FloatField(default=0.05),
        ),
        migrations.AlterField(
            model_name='node',
            name='default_quality',
            field=models.FloatField(default=0.05),
        ),
    ]
