# Generated by Django 5.1.3 on 2025-01-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppl', '0002_remove_node_default_probabilty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='r_score',
            field=models.FloatField(default=0.0),
        ),
    ]
