# Generated by Django 5.1.3 on 2024-11-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppl', '0002_rename_node_id_exercice_node_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Easy'), (1, 'Hard')], default=0),
        ),
    ]
