# Generated by Django 5.1.3 on 2025-01-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppl', '0003_alter_exercice_r_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='quality',
            field=models.FloatField(default=0.2),
        ),
        migrations.AlterField(
            model_name='node',
            name='default_quality',
            field=models.FloatField(default=0.2),
        ),
    ]
