# Generated by Django 5.1.3 on 2024-11-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppl', '0003_alter_node_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='distance',
            field=models.FloatField(),
        ),
    ]
