# Generated by Django 5.1.3 on 2024-11-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppl', '0004_alter_trial_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='r_score',
            field=models.FloatField(),
        ),
    ]
