# Generated by Django 5.1.3 on 2024-11-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppl', '0005_alter_exercice_r_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='category',
            field=models.CharField(choices=[('M', 'Typem'), ('MM', 'Typemm'), ('R', 'Typer'), ('RR', 'Typerr')], default='M', max_length=2),
        ),
    ]
