# Generated by Django 5.1.3 on 2024-12-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppl', '0007_alter_node_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='r_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
