# Generated by Django 5.1.3 on 2025-01-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppl', '0010_alter_student_options_alter_student_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='state',
            field=models.CharField(choices=[('D', 'DEACTIVATED'), ('A', 'ACTIVE'), ('U', 'UNEXPLORED')], default='U', max_length=2),
        ),
        migrations.AlterField(
            model_name='node',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Easy'), (1, 'Hard'), (2, 'Veryhard')], default=0),
        ),
    ]
