# Generated by Django 5.1.3 on 2025-01-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppl', '0011_exercice_is_current_alter_exercice_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='quality',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='node',
            name='default_quality',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='MM_quality',
            field=models.FloatField(default=0.05),
        ),
        migrations.AddField(
            model_name='student',
            name='M_quality',
            field=models.FloatField(default=0.05),
        ),
        migrations.AddField(
            model_name='student',
            name='RM_quality',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='R_quality',
            field=models.FloatField(default=0.0),
        ),
    ]
